Week 3 discussion

#+OPTIONS: num:nil toc:nil author:nil timestamp:nil creator:nil

For our Spam Filter exercise, all of the requirements were given as prose. The
text suggests that a better way to specify required quality attributes is
using attribute scenarios.

Based on the Spam Filter writeup, your work, and discussions, please write one
or two concrete attribute scenarios using format given in the text. Be as
specific as possible. Since the original prose specification is pretty vague,
you may find that you need more specific requirements to write a good
scenario. In that case, it is OK to assume some of these details as long as
they are consistent with the existing requirements, just state what you are
assuming.

For each such scenario, provide a short description of why that scenario is
needed. If it is not obvious, also make clear how to apply the scenario to a
design to objectively decide whether the design satisfies the scenario or not.

Try not to repeat scenarios already given by your classmates (so it will be
easier if you do it earlier).

* Scenario A -- Adaptation
  *Source*: Development team

  *Stimulus*: Wishes to deploy a new spam filter algorithm

  *Artifact*: Installed systems

  *Environment*: Normal operation

  *Response*: New filter is discovered and installed

  *Response Measure*: 90% or more of reporting systems are using the new
  filter within 24 hours.

  /(For this scenario, I assumed that a live-update feature was required for
  the system.  This seems like a reasonable assumption given my experience with spam filters.)/
  
* Scenario B -- Various Clients
  *Source*: Customer

  *Stimulus*: New POP3/IMAP & SMTP-compliant user-agent encountered

  *Artifact*: Process

  *Environment*: Normal operation

  *Response*: Functions normally

  *Response Measure*: No errors
  
  /(This is to meet the anticipated mobile-device need.  I assumed this was an
  actual requirement, rather than a vague desire as given in the document.)/
