* Discussion 1
  Diagnose your community/project team. Using the action notebook tools in Wenger, White, and Smith,
  Chapter 10, select a community or project team you are currently working with or have worked with
  in the past and complete Step 1 - Understand your Community (p. 149-151). Feel free to take this
  further, including responses to Step 2 and Step 3. Note: It is not necessary for you to create the
  forms and attach them to the discussion board. Just answer the questions in the forms and tell us
  about your community/team.
** TODO My post
* Discussion 2
  Ancona & Bresman's final chapter (9) looks at the team from the perspective of leadership. They
  suggest that the best way to lead the extreme team (which I have come to think of as the
  distributed team) is by distributing leadership. They do not suggest abdicating authority or
  responsibility, but instead acting more as a servant leader as distributed team members are
  empowered and held accountable to behave as leaders themselves. Read through the four capabilities
  on pages 222-224 and think about how YOU can apply these strategies to the team that you lead. You
  can relate an example of how you do this now, or how you think you might do it in the future.
** TODO My post
