#+OPTIONS: num:nil toc:nil author:nil timestamp:nil creator:nil

Exam #2

1. Answer the following questions about testing:
(Points: 20)  
  	a. What is the difference between system testing and acceptance testing? Why isn’t it a good idea to have acceptance testing done by the same team that performs system testing?

b. What is the difference between system testing and integration testing? Can you do both at the same time?

c. Assume that you are put in charge of testing a brand new product; what approach to testing would you take? In other words, what is the sequence of activities that you will plan in order to ensure adequate testing of the software? I’m not interested in reading about how you will actually test the software, but how you will create a plan that adequately conveys your strategy for testing.


2. Given this simulated code fragment, answer the following questions.
(Points: 20)  
  	read InputNumber;

if (InputNumber > 0) then
write InputNumber;
else
write “Number is zero or less”;
end if;


while (InputNumber > 10) then
if InputNumber mod 10 == 0 then
write “Evenly divisible by 10”
else
write “Not evenly divisible by 10”
end if;
InputNumber = InputNumber – 1;
end while;



a. How many basis paths are there?

b. Describe each path.

c. How many test cases are required to achieve minimal (basis) path coverage of this code?



3. McConnell (Code Complete) asserts that reviews are usually better at finding defects than testing is.
(Points: 20)  
  	a. Does this imply that testing is superfluous? Why or why not?

b. Briefly discuss the role of reviews in an overall testing approach, and the difference in the types of defects that each approach finds.



4. If the current failure rate for your project is 20 failures/week, which is better than the initial rate of 30 failures/week, and the total number of failures found so far is 140:
(Points: 20)  
  	a. How many more failures do you anticipate finding before releasing the code (i.e., there are no failures according to the assumption by the model) if you use the basic reliability model? State your assumptions, and show your work.

b. Is the assumption (in the basic reliability model) that eventually there will be no failures a realistic assumption? Why or why not?



5. Answer the following questions about Operational Testing:
(Points: 20)  
  	a. Why is operational testing important?

b. What specific types of problems can be found using an operational test approach?

c. Discuss a specific real-life example of a fault that could have been discovered during operational testing but wasn’t discovered until it was used in the field. Please provide specifics as to the nature of the failure as well as the determined root cause. How could this problem have been averted?

