Week 8
#+OPTIONS: num:nil toc:nil author:nil timestamp:nil


* Topic                                                            :noexport:

  BECAUSE AN ASSIGNMENT IS DUE SUNDAY, REBUTTALS TO MAIN POSTS ARE OPTIONAL THIS WEEK - BUT CAPTAINS
  ARE STILL EXPECTED TO CONSOLIDATE.

  The day before Christmas the customer presses the SPM to schedule the detailed status briefing for
  January 4th which the SPM agrees to. Fortunately, the team has started to pull the critical
  information together, however, there is still much work to be done. The SPM has no choice but to
  ask the team to prepare for this briefing over the Christmas vacation period. The team greatly
  resists initially because of the time of year and because the team leads did not want to see their
  team members waste their time preparing for and supporting another customer briefing. They feel
  that far too much of developers’ time had already been spent in meetings with the customer
  discussing changes and clarifications to requirements specifications, design documents, and so
  on. Besides, they said, it would take a great amount of time to prepare a comprehensive briefing
  because it would be necessary to update the top-level design document - the one presented to the
  customer in early November. However, the team collectively recognizes the critical importance of
  communicating reliable status information to the customer and working together with the customer
  to remove roadblocks and pave the way forward. They work long hard hours over the break to revise
  estimates and provide more visibility into what needs to be done.

  However, as a result of this detailed preparation work, it becomes painfully evident to the SPM
  that the July 1st deadline cannot be met. The SPM recalls Fred Brooks’ warning about adding
  resources to a project that is already late (makes it later). In fact, the SPM’s most optimistic
  completion date for any meaningful delivery works out to be the end of October – four months
  later–and even that date would require an immediate freeze on all requirements! The situation is
  clearly very critical.

  Discussion 9: Preparing for a Critical Meeting, January

  The Software Project Manager is on the edge of major confrontation with the customer.

  a. Has the project team failed to consider any technical, management, or strategic actions that
  could help the stakeholders converge on a workable and mutually acceptable solution?

  b. What should the SPM do to prepare for the meeting to negotiate a reasonable result?


* Missed Considerations

* Preparations



* Replies
  ( No replies necessary; do Assignment #3 instead)
