Week 2 Discussion - Best practice article

#+OPTIONS: num:nil toc:nil author:nil timestamp:nil creator:nil

* Ben Straub - Virtual Teams Building Trust
** My post
   The full title of this article is /Building Trust and Cooperation through Technology Adaptation in
   Virtual Teams: Empirical Field Evidence/, and it is a research study on the topic of software
   management and leadership style.  There are three hypotheses:

   1. Command-and-control (CnC) leadership will result in lower trust than a more facilitative
      method.

   2. Facilitative leadership will result in higher levels of technological adaptation than CnC.

   3. Technological adaptation is positively correlated to trust and cooperation.

   Here, "technological adaptation" means changing the use of technology that the team uses to
   communicate.  This includes things like version control, wikis, synchronous meeting software
   (i.e. Elluminate), and others.

   Hypotheses 2 and 3 are borne out; facilitative ("Theory Y") interventions do indeed result in more
   adaptation of communication technology, and adaptation is positively correlated with trust and
   cooperation.  Surprisingly, CnC-style interventions are just as effective at producing trust as
   facilitative leadership is.

   This last conclusion is a bit counter-intuitive, but in hindsight it makes sense; people are more
   willing to follow a leader who is decisive and accountable than one who is wishy-washy and pushes
   all the decisions onto the rest of the team.  It's also clear that both styles of leadership have
   their place, and are not mutually exclusive; some situations call for an edict, others for
   consensus.

** Me -> Dan
   /Would you agree that CnC style of leadership at the begining stages 2 stages and the
   facilitative style at the final two stages would be the way that most teams are likely operate?/

   I don't think so.  My intuition says that both styles of leadership are effective at all phases
   of team formation.  For example, in the /forming/ stage, a CnC action would be that of assigning
   team members in the first place, where a facilitative action might be providing space and desks,
   and allowing the team to arrange themselves physically.

   In the end the two concepts are orthogonal.  The leader will choose, from moment to moment, which
   style of intervention she will use, and their judgment probably won't be impacted by which
   Tuckman phase their team is going through.

** Ori
   This sounds like a good overview, and probably good background reading for this class.  Did the
   author's recommendations agree with your own experience?  Where did you think she was wrong?

** Johnny
   * /Use technology to simulate reality to coordinate efforts/

   I always wonder when people try do to this.  Certainly there are aspects of human nature that are
   better harnessed than thrown away, but shouldn't we use technology to /augment/ our human selves?
   There was some mention of how the use of technology was superior to the face-to-face ways it
   replaced (e.g. threaded forums rather than tangents at meetings), but this line caught my eye.

   Did you notice that the authors were trying to use remote technology to make work better, or just
   working around its limitations to make work more like co-location?
* Ben Straub - Tuckman Article
** My post
   /Why do you believe that this model is still the prominent and most used model for team development?/

   Psychological theory is timeless, at least on the time spans our industry deals with.  What was
   true of humans 45 years ago is still largely true today.

   It's also probably partly due to good marketing.  The findings are sound-bite friendly, easily
   remembered with the mnemonic, and ring true against both experience and intuition.

   /In what ways is it a model that is ubiquitous in terms of its application across time, industries, and cultures?/

   It is based upon studies from widely disparate fields of research, different group settings, and
   that were published over the course of 30 years (1932 - 1964).  Since the subject material is so
   varied, it makes sense that the findings would apply to a wide range of situations.

   /What do you see as the limitations to this model for current application, especially related to
   Distributed SE Teams? In other words, what is it missing? Where does it fall short (if anywhere)?/

   The main limitation of these studies is that the groups were static.  In my experience, groups in
   software development are rarely formed all at once, and are seldom completely disbanded after a
   set amount of time.  People come and go, sometimes to the extent that a group may have more new
   people than original members by the time a project is completed.  This situation doesn't lend
   itself to four discrete phases of group cohesion.

   /How do you see Ancona & Bresman's theory of x-teams relating to, supporting, or contradicting
   Tuckman's model? Please use examples from your own team experiences to explain and justify your opinions./

   The x-teams case studies seem to bear out Tuckman's findings, at least in my opinion.
   Internally-focused teams spend a lot of effort getting to the the fourth stage as quickly as
   possible, with the idea that they should spend more time /performing/.

   On the other hand, externally-focused teams use the uncertainty and organicness of the first two
   phases to find the correct purpose for the group.  Including external entities also has the effect
   of enlarging the group that coheres; core team members are not the only people who get to the
   /performing/ stage.  The theme here is that pointing the ship in the right direction is more
   important than quickly getting up to speed.
** Me -> Dan
   /Even in a dynamic model of team behaviour do you know think that the four stages are adequate
   and are only repeated in more iterations?/

   I guess I was thinking of the model as including the linear progression through the stages.  I
   suppose you could think of a dynamic team that's constantly changing members as bouncing back and
   forth through the stages in a non-linear fashion.

   I still wonder if it's more complicated than that.  Is it necessarily the case that the entire
   team is at the same phase at the same time?  Larger teams especially will have subgroups that are
   in a different place than the rest of the team.  Can you truly think of the team as one thing,
   that has one position on the Tuckman phase line?

   I think that the range of things we call a "team" has grown such that we can't make the same
   assumptions all of Tuckman's source material did.  The four phases are a decent guideline as far
   as they go, but more complicated situations demand either a more complicated model, or no
   simplistic model at all.

** Me -> Kathy
   /It is common for a team to loop back to the storming phase when new members enter or there are
   other significant changes./

   I've actually experienced this first hand.  A couple of years ago our team had several of its
   most senior members move on to other opportunities, and we simultaneously had several openings to
   grow the team.  The end result was there are now more team members that hired on *after* that
   transition than were there *before*.  Our culture now is totally different, and in hindsight I
   remember going through the early phases of group formation.

   I wonder what fraction of a team needs to change to trigger the need for those early stages.  A
   new member on a team of ten probably wouldn't, but replacing five probably would, so it's
   somewhere between 10% and 50%.

** Nick
   /Simplicity is one of the design principles that facilitate having a more easily understood and
   maintainable system. [...] Tuckman's model seems to be simple and makes sense./

   Interesting angle.  I wonder if it's really /simplicity/, so much as it is /generality/.

   In software, a more general solution usually takes /more/ effort and /more/ code, but with human
   language it often takes /fewer/ words to make a more general statement.  Tuckman's model is just
   so, stated in very general terms, using very few words.  And since it is so general and
   non-specific, it can be applied to many situations.

   If Tuckman had written his model to be more concrete and specific, it would have lost much of its
   brevity, and (perhaps?) much of its popularity and power.
   
** Ayellet -> Kooth -> Andrew
   /It may be that we have adjusted accordingly over the intervening years, but I would guess that
   the studies examined were not based on groups as culturally diverse as, say, this class./

   That's true, but I still disagree with Koothapiran's statement.

   Think about what the *forming* and *storming* stages are.  At the beginning, you have just a
   bunch of people who have perhaps never met; at the end, they have all become accustomed to each
   other, and are ready to find a way to work together.  This transition will happen whether the
   people all went to high school together, or don't even speak the same language, because the pre-
   and post-conditions are the same.

   Ayellet said that the stages might "take longer", and my intuition says that's correct.  The only
   case where this wouldn't be true is if the group fails to jell, and falls apart before truly
   becoming a team; we certainly can't expect Tuckman's model to apply to /that/ kind of situation.
